import type { Metadata } from 'next';
import { Figtree, Spline_Sans_Mono } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { TooltipProvider } from '@/components/ui/tooltip';
import { ThemeProvider } from '@/components/theme-provider';
import { Providers } from '@/components/providers';

const figtree = Figtree({ subsets: ['latin'], variable: '--font-sans' });

const mono = Spline_Sans_Mono({
    variable: '--font-mono',
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={cn('h-full', 'antialiased', mono.variable, 'font-sans', figtree.variable)}
            suppressHydrationWarning
        >
            <body className="min-h-full flex flex-col">
                <Providers>
                    <TooltipProvider>{children}</TooltipProvider>
                </Providers>
            </body>
        </html>
    );
}
